github.com:
    users:
        zefixed:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: zefixed
